# Generated by Django 3.1.2 on 2020-10-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Collection',
            new_name='BookCollection',
        ),
    ]
