# Generated by Django 3.1.2 on 2020-10-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_auto_20201005_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
